# These are supported funding model platforms

github: MayGo
patreon: Tockler
open_collective: tockler
ko_fi: maigoerit
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://paypal.me/maigoerit'] # Replace with your PayPal.me link
